<a href="https://colab.research.google.com/github/Basu-Sir/EDA_25BDS0265/blob/main/Experiment_5_(04_08_2026)/CreditCard.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
from google.colab import files
uploaded = files.upload()

Saving fraudTest.csv to fraudTest.csv

In [6]:
import pandas as pd
fraud_test_df=pd.read_csv('fraudTest.csv')
fraud_test_df.head()

,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,...,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud
0,0,2020-06-21 12:14:25,2291163933867244,fraud_Kirlin and Sons,personal_care,2.86,Jeff,Elliott,M,351 Darlene Green,...,33.9659,-80.9355,333497,Mechanical engineer,1968-03-19,2da90c7d74bd46a0caf3777415b3ebd3,1371816865,33.986391,-81.200714,0
1,1,2020-06-21 12:14:33,3573030041201292,fraud_Sporer-Keebler,personal_care,29.84,Joanne,Williams,F,3638 Marsh Union,...,40.3207,-110.4360,302,"Sales professional, IT",1990-01-17,324cc204407e99f51b0d6ca0055005e7,1371816873,39.450498,-109.960431,0
2,2,2020-06-21 12:14:53,3598215285024754,"fraud_Swaniawski, Nitzsche and Welch",health_fitness,41.28,Ashley,Lopez,F,9333 Valentine Point,...,40.6729,-73.5365,34496,"Librarian, public",1970-10-21,c81755dbbbea9d5c77f094348a7579be,1371816893,40.495810,-74.196111,0
3,3,2020-06-21 12:15:15,3591919803438423,fraud_Haley Group,misc_pos,60.05,Brian,Williams,M,32941 Krystal Mill Apt. 552,...,28.5697,-80.8191,54767,Set designer,1987-07-25,2159175b9efe66dc301f149d3d5abf8c,1371816915,28.812398,-80.883061,0
4,4,2020-06-21 12:15:17,3526826139003047,fraud_Johnston-Casper,travel,3.19,Nathan,Massey,M,5783 Evan Roads Apt. 465,...,44.2529,-85.0170,1126,Furniture designer,1955-07-06,57ff021bd3f328f8738bb535c302a31b,1371816917,44.959148,-85.884734,0

In [8]:
data_for_cut = fraud_test_df['amt']
import pandas as pd
bins = [0, 50, 200, 1000, data_for_cut.max() + 1]
category = pd.cut(data_for_cut, bins)
print(category)

0           (0.0, 50.0]
1           (0.0, 50.0]
2           (0.0, 50.0]
3         (50.0, 200.0]
4           (0.0, 50.0]
              ...
555714      (0.0, 50.0]
555715    (50.0, 200.0]
555716    (50.0, 200.0]
555717      (0.0, 50.0]
555718      (0.0, 50.0]
Name: amt, Length: 555719, dtype: category
Categories (4, interval[float64, right]): [(0.0, 50.0] < (50.0, 200.0] < (200.0, 1000.0] <
                                           (1000.0, 22769.11]]

In [9]:
print(pd.Series(category).value_counts())

amt
(0.0, 50.0]           288930
(50.0, 200.0]         241440
(200.0, 1000.0]        23766
(1000.0, 22769.11]      1583
Name: count, dtype: int64

In [10]:
bin_names = ['Small Amount', 'Medium Amount', 'Large Amount', 'Very Large Amount']
print(pd.cut(data_for_cut, bins, labels=bin_names))

0          Small Amount
1          Small Amount
2          Small Amount
3         Medium Amount
4          Small Amount
              ...
555714     Small Amount
555715    Medium Amount
555716    Medium Amount
555717     Small Amount
555718     Small Amount
Name: amt, Length: 555719, dtype: category
Categories (4, object): ['Small Amount' < 'Medium Amount' < 'Large Amount' < 'Very Large Amount']

In [11]:
import numpy as np

data_for_equal_bins = fraud_test_df['city_pop']
print(pd.cut(data_for_equal_bins, 5, precision=0))

0         (-2884.0, 581358.0]
1         (-2884.0, 581358.0]
2         (-2884.0, 581358.0]
3         (-2884.0, 581358.0]
4         (-2884.0, 581358.0]
                 ...
555714    (-2884.0, 581358.0]
555715    (-2884.0, 581358.0]
555716    (-2884.0, 581358.0]
555717    (-2884.0, 581358.0]
555718    (-2884.0, 581358.0]
Name: city_pop, Length: 555719, dtype: category
Categories (5, interval[float64, right]): [(-2884.0, 581358.0] < (581358.0, 1162694.0] <
                                           (1162694.0, 1744029.0] < (1744029.0, 2325365.0] <
                                           (2325365.0, 2906700.0]]

In [13]:
fraud_train_df=pd.read_csv('fraudTrain.csv')
fraud_train_df.head()

,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,...,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud
0,0,2019-01-01 00:00:18,2703186189652095,"fraud_Rippin, Kub and Mann",misc_net,4.97,Jennifer,Banks,F,561 Perry Cove,...,36.0788,-81.1781,3495,"Psychologist, counselling",1988-03-09,0b242abb623afc578575680df30655b9,1325376018,36.011293,-82.048315,0
1,1,2019-01-01 00:00:44,630423337322,"fraud_Heller, Gutmann and Zieme",grocery_pos,107.23,Stephanie,Gill,F,43039 Riley Greens Suite 393,...,48.8878,-118.2105,149,Special educational needs teacher,1978-06-21,1f76529f8574734946361c461b024d99,1325376044,49.159047,-118.186462,0
2,2,2019-01-01 00:00:51,38859492057661,fraud_Lind-Buckridge,entertainment,220.11,Edward,Sanchez,M,594 White Dale Suite 530,...,42.1808,-112.2620,4154,Nature conservation officer,1962-01-19,a1a22d70485983eac12b5b88dad1cf95,1325376051,43.150704,-112.154481,0
3,3,2019-01-01 00:01:16,3534093764340240,"fraud_Kutch, Hermiston and Farrell",gas_transport,45.00,Jeremy,White,M,9443 Cynthia Court Apt. 038,...,46.2306,-112.1138,1939,Patent attorney,1967-01-12,6b849c168bdad6f867558c3793159a81,1325376076,47.034331,-112.561071,0
4,4,2019-01-01 00:03:06,375534208663984,fraud_Keeling-Crist,misc_pos,41.96,Tyler,Garcia,M,408 Bradley Rest,...,38.4207,-79.4629,99,Dance movement psychotherapist,1986-03-28,a41d7549acf90789359a9aa5346dcb46,1325376186,38.674999,-78.632459,0

In [16]:
data_for_qcut = fraud_train_df['amt']
category3 = pd.qcut(data_for_qcut, 4)
print(category3)

0             (0.999, 9.65]
1          (83.14, 28948.9]
2          (83.14, 28948.9]
3             (9.65, 47.52]
4             (9.65, 47.52]
                 ...
1296670       (9.65, 47.52]
1296671      (47.52, 83.14]
1296672    (83.14, 28948.9]
1296673      (47.52, 83.14]
1296674       (0.999, 9.65]
Name: amt, Length: 1296675, dtype: category
Categories (4, interval[float64, right]): [(0.999, 9.65] < (9.65, 47.52] < (47.52, 83.14] <
                                           (83.14, 28948.9]]

In [17]:

print(pd.Series(category3).value_counts())

amt
(0.999, 9.65]       324325
(47.52, 83.14]      324151
(83.14, 28948.9]    324112
(9.65, 47.52]       324087
Name: count, dtype: int64

In [18]:
print("Fraud Test DataFrame Info:")
fraud_test_df.info()
print("\nFraud Train DataFrame Info:")
fraud_train_df.info()

print("\nFraud Test DataFrame Head:")
display(fraud_test_df.head())
print("\nFraud Train DataFrame Head:")
display(fraud_train_df.head())

Fraud Test DataFrame Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 555719 entries, 0 to 555718
Data columns (total 23 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   Unnamed: 0             555719 non-null  int64
 1   trans_date_trans_time  555719 non-null  object
 2   cc_num                 555719 non-null  int64
 3   merchant               555719 non-null  object
 4   category               555719 non-null  object
 5   amt                    555719 non-null  float64
 6   first                  555719 non-null  object
 7   last                   555719 non-null  object
 8   gender                 555719 non-null  object
 9   street                 555719 non-null  object
 10  city                   555719 non-null  object
 11  state                  555719 non-null  object
 12  zip                    555719 non-null  int64
 13  lat                    555719 non-null  float64
 14  long                   555719 non-null  float64
 15  city_pop               555719 non-null  int64
 16  job                    555719 non-null  object
 17  dob                    555719 non-null  object
 18  trans_num              555719 non-null  object
 19  unix_time              555719 non-null  int64
 20  merch_lat              555719 non-null  float64
 21  merch_long             555719 non-null  float64
 22  is_fraud               555719 non-null  int64
dtypes: float64(5), int64(6), object(12)
memory usage: 97.5+ MB

Fraud Train DataFrame Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1296675 entries, 0 to 1296674
Data columns (total 23 columns):
 #   Column                 Non-Null Count    Dtype
---  ------                 --------------    -----
 0   Unnamed: 0             1296675 non-null  int64
 1   trans_date_trans_time  1296675 non-null  object
 2   cc_num                 1296675 non-null  int64
 3   merchant               1296675 non-null  object
 4   category               1296675 non-null  object
 5   amt                    1296675 non-null  float64
 6   first                  1296675 non-null  object
 7   last                   1296675 non-null  object
 8   gender                 1296675 non-null  object
 9   street                 1296675 non-null  object
 10  city                   1296675 non-null  object
 11  state                  1296675 non-null  object
 12  zip                    1296675 non-null  int64
 13  lat                    1296675 non-null  float64
 14  long                   1296675 non-null  float64
 15  city_pop               1296675 non-null  int64
 16  job                    1296675 non-null  object
 17  dob                    1296675 non-null  object
 18  trans_num              1296675 non-null  object
 19  unix_time              1296675 non-null  int64
 20  merch_lat              1296675 non-null  float64
 21  merch_long             1296675 non-null  float64
 22  is_fraud               1296675 non-null  int64
dtypes: float64(5), int64(6), object(12)
memory usage: 227.5+ MB

Fraud Test DataFrame Head:

,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,...,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud
0,0,2020-06-21 12:14:25,2291163933867244,fraud_Kirlin and Sons,personal_care,2.86,Jeff,Elliott,M,351 Darlene Green,...,33.9659,-80.9355,333497,Mechanical engineer,1968-03-19,2da90c7d74bd46a0caf3777415b3ebd3,1371816865,33.986391,-81.200714,0
1,1,2020-06-21 12:14:33,3573030041201292,fraud_Sporer-Keebler,personal_care,29.84,Joanne,Williams,F,3638 Marsh Union,...,40.3207,-110.4360,302,"Sales professional, IT",1990-01-17,324cc204407e99f51b0d6ca0055005e7,1371816873,39.450498,-109.960431,0
2,2,2020-06-21 12:14:53,3598215285024754,"fraud_Swaniawski, Nitzsche and Welch",health_fitness,41.28,Ashley,Lopez,F,9333 Valentine Point,...,40.6729,-73.5365,34496,"Librarian, public",1970-10-21,c81755dbbbea9d5c77f094348a7579be,1371816893,40.495810,-74.196111,0
3,3,2020-06-21 12:15:15,3591919803438423,fraud_Haley Group,misc_pos,60.05,Brian,Williams,M,32941 Krystal Mill Apt. 552,...,28.5697,-80.8191,54767,Set designer,1987-07-25,2159175b9efe66dc301f149d3d5abf8c,1371816915,28.812398,-80.883061,0
4,4,2020-06-21 12:15:17,3526826139003047,fraud_Johnston-Casper,travel,3.19,Nathan,Massey,M,5783 Evan Roads Apt. 465,...,44.2529,-85.0170,1126,Furniture designer,1955-07-06,57ff021bd3f328f8738bb535c302a31b,1371816917,44.959148,-85.884734,0

Fraud Train DataFrame Head:

,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,...,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud
0,0,2019-01-01 00:00:18,2703186189652095,"fraud_Rippin, Kub and Mann",misc_net,4.97,Jennifer,Banks,F,561 Perry Cove,...,36.0788,-81.1781,3495,"Psychologist, counselling",1988-03-09,0b242abb623afc578575680df30655b9,1325376018,36.011293,-82.048315,0
1,1,2019-01-01 00:00:44,630423337322,"fraud_Heller, Gutmann and Zieme",grocery_pos,107.23,Stephanie,Gill,F,43039 Riley Greens Suite 393,...,48.8878,-118.2105,149,Special educational needs teacher,1978-06-21,1f76529f8574734946361c461b024d99,1325376044,49.159047,-118.186462,0
2,2,2019-01-01 00:00:51,38859492057661,fraud_Lind-Buckridge,entertainment,220.11,Edward,Sanchez,M,594 White Dale Suite 530,...,42.1808,-112.2620,4154,Nature conservation officer,1962-01-19,a1a22d70485983eac12b5b88dad1cf95,1325376051,43.150704,-112.154481,0
3,3,2019-01-01 00:01:16,3534093764340240,"fraud_Kutch, Hermiston and Farrell",gas_transport,45.00,Jeremy,White,M,9443 Cynthia Court Apt. 038,...,46.2306,-112.1138,1939,Patent attorney,1967-01-12,6b849c168bdad6f867558c3793159a81,1325376076,47.034331,-112.561071,0
4,4,2019-01-01 00:03:06,375534208663984,fraud_Keeling-Crist,misc_pos,41.96,Tyler,Garcia,M,408 Bradley Rest,...,38.4207,-79.4629,99,Dance movement psychotherapist,1986-03-28,a41d7549acf90789359a9aa5346dcb46,1325376186,38.674999,-78.632459,0

In [19]:
from sklearn.preprocessing import MinMaxScaler

numerical_cols = ['amt', 'lat', 'long', 'city_pop', 'unix_time', 'merch_lat', 'merch_long']

In [20]:
scaler = MinMaxScaler()

# Create a copy to avoid modifying the original DataFrame directly
fraud_test_df_normalized = fraud_test_df.copy()

# Apply scaler to the numerical columns
fraud_test_df_normalized[numerical_cols] = scaler.fit_transform(fraud_test_df_normalized[numerical_cols])

print("Fraud Test DataFrame (Normalized - First 5 rows):")
display(fraud_test_df_normalized.head())

Fraud Test DataFrame (Normalized - First 5 rows):

,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,...,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud
0,0,2020-06-21 12:14:25,2291163933867244,fraud_Kirlin and Sons,personal_care,0.000082,Jeff,Elliott,M,351 Darlene Green,...,0.305255,0.867121,0.114727,Mechanical engineer,1968-03-19,2da90c7d74bd46a0caf3777415b3ebd3,0.000000e+00,0.313922,0.857112,0
1,1,2020-06-21 12:14:33,3573030041201292,fraud_Sporer-Keebler,personal_care,0.001267,Joanne,Williams,F,3638 Marsh Union,...,0.444423,0.565239,0.000096,"Sales professional, IT",1990-01-17,324cc204407e99f51b0d6ca0055005e7,4.785402e-07,0.428589,0.568706,0
2,2,2020-06-21 12:14:53,3598215285024754,"fraud_Swaniawski, Nitzsche and Welch",health_fitness,0.001769,Ashley,Lopez,F,9333 Valentine Point,...,0.452136,0.942836,0.011860,"Librarian, public",1970-10-21,c81755dbbbea9d5c77f094348a7579be,1.674891e-06,0.450526,0.927355,0
3,3,2020-06-21 12:15:15,3591919803438423,fraud_Haley Group,misc_pos,0.002594,Brian,Williams,M,32941 Krystal Mill Apt. 552,...,0.187080,0.868312,0.018834,Set designer,1987-07-25,2159175b9efe66dc301f149d3d5abf8c,2.990876e-06,0.205343,0.860298,0
4,4,2020-06-21 12:15:17,3526826139003047,fraud_Johnston-Casper,travel,0.000096,Nathan,Massey,M,5783 Evan Roads Apt. 465,...,0.530537,0.825355,0.000379,Furniture designer,1955-07-06,57ff021bd3f328f8738bb535c302a31b,3.110511e-06,0.544191,0.810140,0

In [21]:
scaler = MinMaxScaler()

# Create a copy to avoid modifying the original DataFrame directly
fraud_train_df_normalized = fraud_train_df.copy()

# Apply scaler to the numerical columns
fraud_train_df_normalized[numerical_cols] = scaler.fit_transform(fraud_train_df_normalized[numerical_cols])

print("Fraud Train DataFrame (Normalized - First 5 rows):")
display(fraud_train_df_normalized.head())

Fraud Train DataFrame (Normalized - First 5 rows):

,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,...,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud
0,0,2019-01-01 00:00:18,2703186189652095,"fraud_Rippin, Kub and Mann",misc_net,0.000137,Jennifer,Banks,F,561 Perry Cove,...,0.343968,0.864638,0.001194,"Psychologist, counselling",1988-03-09,0b242abb623afc578575680df30655b9,0.000000e+00,0.350302,0.848602,0
1,1,2019-01-01 00:00:44,630423337322,"fraud_Heller, Gutmann and Zieme",grocery_pos,0.003670,Stephanie,Gill,F,43039 Riley Greens Suite 393,...,0.618450,0.485682,0.000043,Special educational needs teacher,1978-06-21,1f76529f8574734946361c461b024d99,5.598526e-07,0.621488,0.486208,0
2,2,2019-01-01 00:00:51,38859492057661,fraud_Lind-Buckridge,entertainment,0.007569,Edward,Sanchez,M,594 White Dale Suite 530,...,0.474727,0.546553,0.001421,Nature conservation officer,1962-01-19,a1a22d70485983eac12b5b88dad1cf95,7.105821e-07,0.497559,0.546697,0
3,3,2019-01-01 00:01:16,3534093764340240,"fraud_Kutch, Hermiston and Farrell",gas_transport,0.001520,Jeremy,White,M,9443 Cynthia Court Apt. 038,...,0.561509,0.548070,0.000659,Patent attorney,1967-01-12,6b849c168bdad6f867558c3793159a81,1.248902e-06,0.577663,0.542619,0
4,4,2019-01-01 00:03:06,375534208663984,fraud_Keeling-Crist,misc_pos,0.001415,Tyler,Garcia,M,408 Bradley Rest,...,0.394153,0.882190,0.000026,Dance movement psychotherapist,1986-03-28,a41d7549acf90789359a9aa5346dcb46,3.617509e-06,0.405244,0.882857,0

In [22]:
from sklearn.preprocessing import StandardScaler

# Define numerical columns to standardize (same as for min-max scaling)
numerical_cols = ['amt', 'lat', 'long', 'city_pop', 'unix_time', 'merch_lat', 'merch_long']

In [23]:
scaler_standard = StandardScaler()

# Create a copy to avoid modifying the original DataFrame directly
fraud_test_df_standardized = fraud_test_df.copy()

# Apply scaler to the numerical columns
fraud_test_df_standardized[numerical_cols] = scaler_standard.fit_transform(fraud_test_df_standardized[numerical_cols])

print("Fraud Test DataFrame (Standardized - First 5 rows):")
display(fraud_test_df_standardized.head())

Fraud Test DataFrame (Standardized - First 5 rows):

,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,...,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud
0,0,2020-06-21 12:14:25,2291163933867244,fraud_Kirlin and Sons,personal_care,-0.424463,Jeff,Elliott,M,351 Darlene Green,...,-0.904377,0.677451,0.816521,Mechanical engineer,1968-03-19,2da90c7d74bd46a0caf3777415b3ebd3,-1.703871,-0.894145,0.657586,0
1,1,2020-06-21 12:14:33,3573030041201292,fraud_Sporer-Keebler,personal_care,-0.252337,Joanne,Williams,F,3638 Marsh Union,...,0.351182,-1.472454,-0.292685,"Sales professional, IT",1990-01-17,324cc204407e99f51b0d6ca0055005e7,-1.703869,0.178126,-1.436610,0
2,2,2020-06-21 12:14:53,3598215285024754,"fraud_Swaniawski, Nitzsche and Welch",health_fitness,-0.179353,Ashley,Lopez,F,9333 Valentine Point,...,0.420768,1.216667,-0.178853,"Librarian, public",1970-10-21,c81755dbbbea9d5c77f094348a7579be,-1.703865,0.383257,1.167640,0
3,3,2020-06-21 12:15:15,3591919803438423,fraud_Haley Group,misc_pos,-0.059605,Brian,Williams,M,32941 Krystal Mill Apt. 552,...,-1.970539,0.685934,-0.111371,Set designer,1987-07-25,2159175b9efe66dc301f149d3d5abf8c,-1.703861,-1.909485,0.680717,0
4,4,2020-06-21 12:15:17,3526826139003047,fraud_Johnston-Casper,travel,-0.422358,Nathan,Massey,M,5783 Evan Roads Apt. 465,...,1.128092,0.380004,-0.289942,Furniture designer,1955-07-06,57ff021bd3f328f8738bb535c302a31b,-1.703861,1.259139,0.316510,0

In [24]:
scaler_standard = StandardScaler()

# Create a copy to avoid modifying the original DataFrame directly
fraud_train_df_standardized = fraud_train_df.copy()

# Apply scaler to the numerical columns
fraud_train_df_standardized[numerical_cols] = scaler_standard.fit_transform(fraud_train_df_standardized[numerical_cols])

print("Fraud Train DataFrame (Standardized - First 5 rows):")
display(fraud_train_df_standardized.head())

Fraud Train DataFrame (Standardized - First 5 rows):

,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,...,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud
0,0,2019-01-01 00:00:18,2703186189652095,"fraud_Rippin, Kub and Mann",misc_net,-0.407826,Jennifer,Banks,F,561 Perry Cove,...,-0.484420,0.657620,-0.282589,"Psychologist, counselling",1988-03-09,0b242abb623afc578575680df30655b9,-1.858664,-0.494354,0.593864,0
1,1,2019-01-01 00:00:44,630423337322,"fraud_Heller, Gutmann and Zieme",grocery_pos,0.230039,Stephanie,Gill,F,43039 Riley Greens Suite 393,...,2.039120,-2.033870,-0.293670,Special educational needs teacher,1978-06-21,1f76529f8574734946361c461b024d99,-1.858662,2.078699,-2.030341,0
2,2,2019-01-01 00:00:51,38859492057661,fraud_Lind-Buckridge,entertainment,0.934149,Edward,Sanchez,M,594 White Dale Suite 530,...,0.717754,-1.601537,-0.280406,Nature conservation officer,1962-01-19,a1a22d70485983eac12b5b88dad1cf95,-1.858662,0.902849,-1.592323,0
3,3,2019-01-01 00:01:16,3534093764340240,"fraud_Kutch, Hermiston and Farrell",gas_transport,-0.158132,Jeremy,White,M,9443 Cynthia Court Apt. 038,...,1.515617,-1.590766,-0.287742,Patent attorney,1967-01-12,6b849c168bdad6f867558c3793159a81,-1.858660,1.662886,-1.621848,0
4,4,2019-01-01 00:03:06,375534208663984,fraud_Keeling-Crist,misc_pos,-0.177094,Tyler,Garcia,M,408 Bradley Rest,...,-0.023035,0.782279,-0.293835,Dance movement psychotherapist,1986-03-28,a41d7549acf90789359a9aa5346dcb46,-1.858651,0.026941,0.841909,0

In [25]:
# Count fraud transactions in fraud_test_df
fraud_test_count = fraud_test_df['is_fraud'].sum()
print(f"Number of fraud transactions in fraud_test_df: {fraud_test_count}")

Number of fraud transactions in fraud_test_df: 2145

In [26]:
# Count fraud transactions in fraud_train_df
fraud_train_count = fraud_train_df['is_fraud'].sum()
print(f"Number of fraud transactions in fraud_train_df: {fraud_train_count}")

Number of fraud transactions in fraud_train_df: 7506

In [27]:
# Calculate total fraud transactions
total_fraud_count = fraud_test_count + fraud_train_count
print(f"Total number of fraud transactions across both datasets: {total_fraud_count}")

Total number of fraud transactions across both datasets: 9651