<a href="https://colab.research.google.com/github/Basu-Sir/EDA_25BDS0265/blob/main/Experiment_4_(28_07_2026)/Merging%20and%20Grouping%20Data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd


df1WC = pd.DataFrame({
    'JerseyNumber': [9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29],
    'PlayerNameWC': ['Joselu', 'Ferran Torres', 'Alex Remiro', 'Alex Baena', 'Nico Williams',
                     'Lamine Yamal', 'Mikel Oyarzabal', 'Unai Simon', 'Fermín López',
                     'Pau Cubarsí', 'Marcos Llorente']
})

df2WC = pd.DataFrame({
    'JerseyNumber': [2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30],
    'PlayerNameWC': ['Dani Carvajal', 'Nacho', 'Mikel Merino', 'Fabián Ruiz', 'Dani Olmo',
                     'Alejandro Grimaldo', 'Aymeric Laporte', 'Rodri', 'Martín Zubimendi',
                     'Pedri', 'Jesús Navas', 'Marc Cucurella', 'Ayoze Pérez', 'Aleix García',
                     'Kepa Arrizabalaga']
})


df1PL = pd.DataFrame({
    'JerseyNumber': [1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29],
    'PlayerNamePL': ['David Raya', 'Robin Le Normand', 'Dani Vivian', 'Álvaro Morata',
                     'Joselu', 'Ferran Torres', 'Alex Remiro', 'Alex Baena', 'Nico Williams',
                     'Lamine Yamal', 'Mikel Oyarzabal', 'Unai Simon', 'Fermín López',
                     'Pau Cubarsí', 'Marcos Llorente']
})

df2PL = pd.DataFrame({
    'JerseyNumber': [2, 4, 6, 8, 10, 12, 14, 16, 18, 20],
    'PlayerNamePL': ['Dani Carvajal', 'Nacho', 'Mikel Merino', 'Fabián Ruiz', 'Dani Olmo',
                     'Alejandro Grimaldo', 'Aymeric Laporte', 'Rodri', 'Martín Zubimendi',
                     'Pedri']
})

In [2]:
dfWC = pd.concat([df1WC, df2WC], ignore_index=True)
dfPL = pd.concat([df1PL, df2PL], ignore_index=True)

df = dfWC.merge(dfPL, how='inner')
df

    JerseyNumber        PlayerNameWC        PlayerNamePL
0              9              Joselu              Joselu
1             11       Ferran Torres       Ferran Torres
2             13         Alex Remiro         Alex Remiro
3             15          Alex Baena          Alex Baena
4             17       Nico Williams       Nico Williams
5             19        Lamine Yamal        Lamine Yamal
6             21     Mikel Oyarzabal     Mikel Oyarzabal
7             23          Unai Simon          Unai Simon
8             25        Fermín López        Fermín López
9             27         Pau Cubarsí         Pau Cubarsí
10            29     Marcos Llorente     Marcos Llorente
11             2       Dani Carvajal       Dani Carvajal
12             4               Nacho               Nacho
13             6        Mikel Merino        Mikel Merino
14             8         Fabián Ruiz         Fabián Ruiz
15            10           Dani Olmo           Dani Olmo
16            12  Alejandro Grimaldo  Alejandro Grimaldo
17            14     Aymeric Laporte     Aymeric Laporte
18            16               Rodri               Rodri
19            18    Martín Zubimendi    Martín Zubimendi
20            20               Pedri               Pedri

In [3]:
dfWC = pd.concat([df1WC, df2WC], ignore_index=True)
dfPL = pd.concat([df1PL, df2PL], ignore_index=True)

df = dfWC.merge(dfPL, how='left')
df

    JerseyNumber        PlayerNameWC        PlayerNamePL
0              9              Joselu              Joselu
1             11       Ferran Torres       Ferran Torres
2             13         Alex Remiro         Alex Remiro
3             15          Alex Baena          Alex Baena
4             17       Nico Williams       Nico Williams
5             19        Lamine Yamal        Lamine Yamal
6             21     Mikel Oyarzabal     Mikel Oyarzabal
7             23          Unai Simon          Unai Simon
8             25        Fermín López        Fermín López
9             27         Pau Cubarsí         Pau Cubarsí
10            29     Marcos Llorente     Marcos Llorente
11             2       Dani Carvajal       Dani Carvajal
12             4               Nacho               Nacho
13             6        Mikel Merino        Mikel Merino
14             8         Fabián Ruiz         Fabián Ruiz
15            10           Dani Olmo           Dani Olmo
16            12  Alejandro Grimaldo  Alejandro Grimaldo
17            14     Aymeric Laporte     Aymeric Laporte
18            16               Rodri               Rodri
19            18    Martín Zubimendi    Martín Zubimendi
20            20               Pedri               Pedri
21            22         Jesús Navas                 NaN
22            24      Marc Cucurella                 NaN
23            26         Ayoze Pérez                 NaN
24            28        Aleix García                 NaN
25            30   Kepa Arrizabalaga                 NaN

In [4]:
dfWC = pd.concat([df1WC, df2WC], ignore_index=True)
dfPL = pd.concat([df1PL, df2PL], ignore_index=True)

df = dfWC.merge(dfPL, how='right')
df

    JerseyNumber        PlayerNameWC        PlayerNamePL
0              1                 NaN          David Raya
1              3                 NaN    Robin Le Normand
2              5                 NaN         Dani Vivian
3              7                 NaN       Álvaro Morata
4              9              Joselu              Joselu
5             11       Ferran Torres       Ferran Torres
6             13         Alex Remiro         Alex Remiro
7             15          Alex Baena          Alex Baena
8             17       Nico Williams       Nico Williams
9             19        Lamine Yamal        Lamine Yamal
10            21     Mikel Oyarzabal     Mikel Oyarzabal
11            23          Unai Simon          Unai Simon
12            25        Fermín López        Fermín López
13            27         Pau Cubarsí         Pau Cubarsí
14            29     Marcos Llorente     Marcos Llorente
15             2       Dani Carvajal       Dani Carvajal
16             4               Nacho               Nacho
17             6        Mikel Merino        Mikel Merino
18             8         Fabián Ruiz         Fabián Ruiz
19            10           Dani Olmo           Dani Olmo
20            12  Alejandro Grimaldo  Alejandro Grimaldo
21            14     Aymeric Laporte     Aymeric Laporte
22            16               Rodri               Rodri
23            18    Martín Zubimendi    Martín Zubimendi
24            20               Pedri               Pedri

In [5]:
dfWC = pd.concat([df1WC, df2WC], ignore_index=True)
dfPL = pd.concat([df1PL, df2PL], ignore_index=True)

df = pd.concat([dfPL, dfWC], axis=1)
df

    JerseyNumber        PlayerNamePL  JerseyNumber        PlayerNameWC
0            1.0          David Raya             9              Joselu
1            3.0    Robin Le Normand            11       Ferran Torres
2            5.0         Dani Vivian            13         Alex Remiro
3            7.0       Álvaro Morata            15          Alex Baena
4            9.0              Joselu            17       Nico Williams
5           11.0       Ferran Torres            19        Lamine Yamal
6           13.0         Alex Remiro            21     Mikel Oyarzabal
7           15.0          Alex Baena            23          Unai Simon
8           17.0       Nico Williams            25        Fermín López
9           19.0        Lamine Yamal            27         Pau Cubarsí
10          21.0     Mikel Oyarzabal            29     Marcos Llorente
11          23.0          Unai Simon             2       Dani Carvajal
12          25.0        Fermín López             4               Nacho
13          27.0         Pau Cubarsí             6        Mikel Merino
14          29.0     Marcos Llorente             8         Fabián Ruiz
15           2.0       Dani Carvajal            10           Dani Olmo
16           4.0               Nacho            12  Alejandro Grimaldo
17           6.0        Mikel Merino            14     Aymeric Laporte
18           8.0         Fabián Ruiz            16               Rodri
19          10.0           Dani Olmo            18    Martín Zubimendi
20          12.0  Alejandro Grimaldo            20               Pedri
21          14.0     Aymeric Laporte            22         Jesús Navas
22          16.0               Rodri            24      Marc Cucurella
23          18.0    Martín Zubimendi            26         Ayoze Pérez
24          20.0               Pedri            28        Aleix García
25           NaN                 NaN            30   Kepa Arrizabalaga

In [6]:
df.head(10)

   JerseyNumber      PlayerNamePL  JerseyNumber     PlayerNameWC
0           1.0        David Raya             9           Joselu
1           3.0  Robin Le Normand            11    Ferran Torres
2           5.0       Dani Vivian            13      Alex Remiro
3           7.0     Álvaro Morata            15       Alex Baena
4           9.0            Joselu            17    Nico Williams
5          11.0     Ferran Torres            19     Lamine Yamal
6          13.0       Alex Remiro            21  Mikel Oyarzabal
7          15.0        Alex Baena            23       Unai Simon
8          17.0     Nico Williams            25     Fermín López
9          19.0      Lamine Yamal            27      Pau Cubarsí

In [7]:
df.describe()

       JerseyNumber  JerseyNumber
count     25.000000     26.000000
mean      13.400000     17.269231
std        8.025999      8.042675
min        1.000000      2.000000
25%        7.000000     11.250000
50%       13.000000     17.500000
75%       19.000000     23.750000
max       29.000000     30.000000

In [8]:
import numpy as np
data = np.arange(15).reshape((3,5))
indexers = ['Rainfall', 'Humidity', 'Wind']
dframe1 = pd.DataFrame(data, index=indexers, columns=['Bombay', 'Delhi', 'Madras', 'Kolkata', 'Ahmedabad'])
dframe1

          Bombay  Delhi  Madras  Kolkata  Ahmedabad
Rainfall       0      1       2        3          4
Humidity       5      6       7        8          9
Wind          10     11      12       13         14

In [9]:
stacked = dframe1.stack()
stacked

Rainfall  Bombay        0
          Delhi         1
          Madras        2
          Kolkata       3
          Ahmedabad     4
Humidity  Bombay        5
          Delhi         6
          Madras        7
          Kolkata       8
          Ahmedabad     9
Wind      Bombay       10
          Delhi        11
          Madras       12
          Kolkata      13
          Ahmedabad    14
dtype: int64

In [10]:
stacked.unstack()

          Bombay  Delhi  Madras  Kolkata  Ahmedabad
Rainfall       0      1       2        3          4
Humidity       5      6       7        8          9
Wind          10     11      12       13         14

In [11]:

series1 = pd.Series([000, 111, 222, 333], index=['zeros','ones', 'twos', 'threes'])
series2 = pd.Series([444, 555, 666], index=['fours', 'fives', 'sixs'])

frame2 = pd.concat([series1, series2], keys=['Number1', 'Number2'])
frame2.unstack()

         fives  fours   ones   sixs  threes   twos  zeros
Number1    NaN    NaN  111.0    NaN   333.0  222.0    0.0
Number2  555.0  444.0    NaN  666.0     NaN    NaN    NaN